baseURL = 'https://www.regina23.com/'
languageCode = "zh-cn"
title = "Regina23's Blog"
theme = "LoveIt"

# Author config
# 作者配置
[author]
  name = "Regina"
  email = ""
  link = ""

[params]
  # website title for Open Graph and Twitter Cards
  # 网站标题, 用于 Open Graph 和 Twitter Cards
  title = "Regina23's Blog"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  # 网站描述, 用于 RSS, SEO, Open Graph 和 Twitter Cards
  description = "Talk is cheap. Show me the code."
  # website images for Open Graph and Twitter Cards
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  #images = ["/logo.png"]
